server:
  address: 0.0.0.0
  port: 8088

spring:
  application:
    name: woodwhales-rbac
  profiles:
    active: @profiles.active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
